import Head from "next/head";
import DevelopProjetion from "../components/Layouts/DevelopProjection";

export default function Home() {
  return (
    <>
      <Head>
        <title>MM Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/LogoMMdevFavicon.jpeg" />
      </Head>
      <main>
        <div>
          <DevelopProjetion />
        </div>
      </main>
    </>
  );
}
